title: cassandra zhou
url: "https://runxinz.github.io"
baseurl: ""  
markdown: kramdown
#ins_logo: "./bits-logo.png"  # Uncomment if you want to add a logo

tracking_id: #  # Add your Google Analytics ID if you want tracking

footer: yes
footer_url: "https://github.com/runxinz"
footer_text: "© 2025 cassandra zhou"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "about"
   link: "/" 
 - name: "other"
   link: "other"

plugins:
  - jekyll-target-blank
